# Generated by Django 3.0.3 on 2020-04-15 12:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('phonenumber', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('category', models.TextField(choices=[('COMPUTER', 'COMPUTER'), ('FURNITURE', 'FURNITURE'), ('OFFICE_EQUIPMENT', 'OFFICE EQUIPMENT'), ('LINK_EQUIPMENTS', 'LINK_EQUIPMENTS'), ('SERVER', 'SERVER')])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('status', models.TextField(default='unapproved', max_length=100)),
                ('comments', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
