# Generated by Django 3.0.3 on 2020-04-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
