# Generated by Django 3.0.3 on 2020-04-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200418_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_approve_order', 'can_reject_order'),)},
        ),
    ]
